; Load the fonts for setup when running Mini-Windows
[fonts]
MS Serif 8,10,12,14,18,24 (VGA res)=SERIFE.FON
MS Sans Serif 8,10,12,14,18,24 (VGA res)=SSERIFE.FON
[colors]
Background=0 0 0
AppWorkspace=255 255 255
Window=192 192 192
WindowText=0 0 0
Menu=192 192 192
MenuText=0 0 0
ActiveTitle=0 0 128
InactiveTitle=130 130 130
TitleText=255 255 255
ActiveBorder=192 192 192
InactiveBorder=130 130 130
WindowFrame=0 0 0
Scrollbar=130 130 130
ButtonFace=192 192 192
ButtonShadow=130 130 130
ButtonText=0 0 0
GrayText=128 128 128
Hilight=0 0 128
HilightText=255 255 255
InactiveTitleText=192 192 192
ButtonHilight=255 255 255

[WindowMetrics]
BorderWidth=3
CaptionHeight=18
CaptionFontName=MS Sans Serif
CaptionFontSize=-13
CaptionFontWeight=400
CaptionFontItalic=0
MenuHeight=18
MenuFontName=MS Sans Serif
MenuFontSize=-11
MenuFontWeight=400
MenuFontItalic=0
SysMenuWidth=19
MinMaxWidth=19
ScrollBarWidth=15
ScrollArrowLength=13